spring:
  application:
    name: file-upload-service
  datasource:
    druid:
      validation-query: SELECT 1 from dual
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://118.31.38.15:3306/Count_Lines?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: countlines
      password: countlines
      initial-size: 5
      max-active: 20
      max-wait: 60000
      min-idle: 5
      #druid监控信息
      filter:
        stat:
          enabled: true
  thymeleaf:
    cache: false
server:
  port: 8091
mybatis:
  type-aliases-package: com.silence.fileupload.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #     打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: NULL
# 文件上传储存的目录
upload-dir: ~/IdeaProjects/uploadFiles